<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semantics_Additional functions-ss-pane-589</name>
   <tag></tag>
   <elementGuidId>9b624095-29b1-41e5-85f2-31338f9f0602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>flt-semantics[aria-label='Additional functions']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-20']/flt-semantics-container/flt-semantics</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>tag[aria-label='aria-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>739fa530-f497-41ec-911c-87b3ae86a449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-21</value>
      <webElementGuid>1af88669-7493-418f-94f1-121238c41779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Additional functions</value>
      <webElementGuid>174a2b74-3999-4d80-a82f-d1f5426bfbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e52c8c85-955f-4204-a128-8e2153efb81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>daca132e-0ee2-4685-90cc-ddfb0f6cca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Additional functions</value>
      <webElementGuid>9cd72054-8320-40f7-bc3a-fd866d1d1899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/flt-semantics-host[1]/flt-semantics[@id=&quot;flt-semantic-node-0&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-1&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-18&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-19&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-20&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-21&quot;]</value>
      <webElementGuid>beb253b6-cabe-41d0-8aeb-3ecfdb70cf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>tag[aria-label='aria-label']</value>
      <webElementGuid>cad5d536-9af1-4926-95c8-32058691423e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Flutter_Web/Page_Retail by Aiden/flt-glass-pane</value>
      <webElementGuid>0869af8a-1cc2-46f0-9a60-12821e9b396d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e17af50-b0ef-4517-84de-1a4a52b793a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-20']/flt-semantics-container/flt-semantics</value>
      <webElementGuid>8341a458-fd3c-4bc3-8a42-3c7c3c9e6e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>04318a6c-0fb4-4d45-b6e9-39200b8a756f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id = 'flt-semantic-node-21' and (text() = 'Additional functions' or . = 'Additional functions')]</value>
      <webElementGuid>2e4040c8-325f-4dcd-a99a-ee1e224fca2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
