<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semanticsflt-semantic-node-236-ss-pane-a16</name>
   <tag></tag>
   <elementGuidId>05722ffb-d652-4c2e-a797-f8923e4623ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-229']/flt-semantics-container/flt-semantics[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flt-semantics-host > #flt-semantic-node-0 > flt-semantics-container > #flt-semantic-node-1 > flt-semantics-container > #flt-semantic-node-126 > flt-semantics-container > #flt-semantic-node-127 > flt-semantics-container > #flt-semantic-node-128 > flt-semantics-container > #flt-semantic-node-129 > flt-semantics-container > #flt-semantic-node-148 > flt-semantics-container > #flt-semantic-node-130 > flt-semantics-container > #flt-semantic-node-229 > flt-semantics-container > #flt-semantic-node-236</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>1f9fa03a-0f66-48ba-bfbb-9ae5d7b6dfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-236</value>
      <webElementGuid>86c8410e-d153-47c2-bfab-31e7b9bc9ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dfb8d776-0d24-4ac5-9d4c-04f9f6e86fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ea9b262-5443-4825-b4c7-adb19a0ad4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/flt-semantics-host[1]/flt-semantics[@id=&quot;flt-semantic-node-0&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-1&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-126&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-127&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-128&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-129&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-148&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-130&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-229&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-236&quot;]</value>
      <webElementGuid>25852312-5c21-4e3f-b694-77491e7c2881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Flutter_Web/Page_Retail by Aiden/flt-glass-pane</value>
      <webElementGuid>4a102654-4bb2-4ba0-81e4-8c6ee7f21984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb1f297b-2220-42ab-944d-1080cf374de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-229']/flt-semantics-container/flt-semantics[7]</value>
      <webElementGuid>28c41a16-17f3-438d-8762-905e838e7655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id = 'flt-semantic-node-236']</value>
      <webElementGuid>950cb311-c65f-4d48-b44f-7cab6a8457af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
