<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-glass-pane</name>
   <tag></tag>
   <elementGuidId>718470d7-2be1-4167-b7b2-a4eaca9a3372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-glass-pane</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flt-glass-pane</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-glass-pane</value>
      <webElementGuid>63128085-3c6a-43eb-84cd-afec54acf5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/flt-glass-pane[1]</value>
      <webElementGuid>0c3ea68c-5409-453b-adf1-a62f3bbc6f4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flt-glass-pane</value>
      <webElementGuid>a7bcf955-9bcc-47d6-a7ea-70574fdcee63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
