<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semantics_Paused Transaction-ss-pane-fcb</name>
   <tag></tag>
   <elementGuidId>e6649514-ffa4-4da0-896b-e3b5a0b1474a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-137']/flt-semantics-container/flt-semantics</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flt-semantics-host > #flt-semantic-node-0 > flt-semantics-container > #flt-semantic-node-1 > flt-semantics-container > #flt-semantic-node-126 > flt-semantics-container > #flt-semantic-node-127 > flt-semantics-container > #flt-semantic-node-128 > flt-semantics-container > #flt-semantic-node-129 > flt-semantics-container > #flt-semantic-node-131 > flt-semantics-container > #flt-semantic-node-132 > flt-semantics-container > #flt-semantic-node-133 > flt-semantics-container > #flt-semantic-node-143 > flt-semantics-container > #flt-semantic-node-137 > flt-semantics-container > #flt-semantic-node-138</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>4aa36dd1-51ba-4e15-b6da-3aecd6a15fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-138</value>
      <webElementGuid>d695818a-e2bf-4a0a-a4b7-f2c7dc00136f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Paused Transaction</value>
      <webElementGuid>7138ca1b-d00c-4c6c-9149-b9133269f155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>01bd7593-2b30-49de-b169-35ecfb26c1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>962c1c5f-2c09-4afe-872f-8bd01fd30d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paused Transaction</value>
      <webElementGuid>cc1bf8c8-09da-48ab-aac4-59241e071ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/flt-semantics-host[1]/flt-semantics[@id=&quot;flt-semantic-node-0&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-1&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-126&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-127&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-128&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-129&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-131&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-132&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-133&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-143&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-137&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-138&quot;]</value>
      <webElementGuid>988b0340-8616-4287-8ba5-4ad40c617eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Flutter_Web/Page_Retail by Aiden/flt-glass-pane</value>
      <webElementGuid>270f8e2e-bdf4-4c66-afc5-72e84d9a74fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d60d5777-386a-43e8-a1e4-5c4896518bc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-137']/flt-semantics-container/flt-semantics</value>
      <webElementGuid>c1eb4b13-5546-4d49-9924-1435a960a40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>47938955-7bbd-4929-bc68-1de092eb35cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id = 'flt-semantic-node-138' and (text() = 'Paused Transaction' or . = 'Paused Transaction')]</value>
      <webElementGuid>21bbff6f-3f6d-46be-a49f-f869c2a00b22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
