<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flt-semantics_Resume-ss-pane-d08</name>
   <tag></tag>
   <elementGuidId>4ffaadd5-2e54-4eb7-b282-34654e4cef04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-119']/flt-semantics-container/flt-semantics</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flt-semantics-host > #flt-semantic-node-0 > flt-semantics-container > #flt-semantic-node-1 > flt-semantics-container > #flt-semantic-node-89 > flt-semantics-container > #flt-semantic-node-93 > flt-semantics-container > #flt-semantic-node-94 > flt-semantics-container > #flt-semantic-node-115 > flt-semantics-container > #flt-semantic-node-125 > flt-semantics-container > #flt-semantic-node-119 > flt-semantics-container > #flt-semantic-node-120</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flt-semantics</value>
      <webElementGuid>9b7add89-b40a-4db4-b021-074c3809e213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flt-semantic-node-120</value>
      <webElementGuid>f97b3b52-a283-4585-a765-a2f9a889a317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Resume</value>
      <webElementGuid>d31d5578-bebe-4c92-b03a-2f8c2215b4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a702a0f7-b866-408d-814d-1364f96f48e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99d343cb-bb90-44ca-8a63-fc2f2c5e53ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resume</value>
      <webElementGuid>d80ca868-8480-4456-9531-78a6ac9b81b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/flt-semantics-host[1]/flt-semantics[@id=&quot;flt-semantic-node-0&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-1&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-89&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-93&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-94&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-115&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-125&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-119&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-120&quot;]</value>
      <webElementGuid>108a64e9-5ee6-465c-904b-f6b02d42b9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Flutter_Web/Page_Retail by Aiden/flt-glass-pane</value>
      <webElementGuid>d94e469c-59a9-4e7e-8dec-2f3f8c2b6fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6af8842d-b52f-4ac9-b1c9-e5edf6050495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-119']/flt-semantics-container/flt-semantics</value>
      <webElementGuid>a8f331d4-fee5-4396-91bc-77e5e045a47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>60682a63-6213-4fb2-b4e7-7e32dd4f03ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//flt-semantics[@id = 'flt-semantic-node-120' and (text() = 'Resume' or . = 'Resume')]</value>
      <webElementGuid>068aacd7-304c-4fa1-bfdb-f5fbd7af5612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
