<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-ss-pane-930</name>
   <tag></tag>
   <elementGuidId>1bfc8ef7-27e6-43eb-aa9e-63b884f7ed84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flt-semantics[@id='flt-semantic-node-330']/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flt-semantics-host > #flt-semantic-node-0 > flt-semantics-container > #flt-semantic-node-1 > flt-semantics-container > #flt-semantic-node-328 > flt-semantics-container > #flt-semantic-node-329 > flt-semantics-container > #flt-semantic-node-330 > input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f469dad2-46f6-406f-8ae6-c8c2dcda0540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>93505866-ff3c-4b0e-9bfa-2e8b5242caea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>fbc204b4-de8a-4bb5-b4ff-6bbdb4d5309b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>988d6670-b057-4c05-994b-d0b7bb19e417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-semantics-role</name>
      <type>Main</type>
      <value>text-field</value>
      <webElementGuid>ddc7aa03-76f4-4680-9c91-a661b786926c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Are you sure you want to e-mail this transaction?
E-mail confirmation</value>
      <webElementGuid>9d03257a-84ef-4f01-9b9d-15db2e79a6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/flt-semantics-host[1]/flt-semantics[@id=&quot;flt-semantic-node-0&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-1&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-328&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-329&quot;]/flt-semantics-container[1]/flt-semantics[@id=&quot;flt-semantic-node-330&quot;]/input[1]</value>
      <webElementGuid>dd0c777b-a015-40f1-aaed-3db6aed2827c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Flutter_Web/Page_Retail by Aiden/flt-glass-pane</value>
      <webElementGuid>ce3604da-1802-44fe-9689-b1c9a233cc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f12cff1c-cb94-4c76-af7a-e66259a8a552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flt-semantics[@id='flt-semantic-node-330']/input</value>
      <webElementGuid>39831a47-ddff-4d8c-b964-63e9d16d91a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
