<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization_Input.Username</name>
   <tag></tag>
   <elementGuidId>a4e6905c-3690-48a0-81a7-a081501bd580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AccountLoginIndexUserName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccountLoginIndexUserName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>060cdca6-607e-4766-9622-670f212bc27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountLoginIndexUserName</value>
      <webElementGuid>a3c47b3b-79af-416d-aacc-b3d823916051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-login</value>
      <webElementGuid>1154358c-84f8-4f61-aab0-df0cff406f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cac938d9-21f6-46a9-a1f2-eb80cb3b74e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3375209d-7b16-4b4a-a190-67d9bf261441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Username field is required.</value>
      <webElementGuid>6179f18c-431e-463e-b666-be5d088ef6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Input.Username</value>
      <webElementGuid>796d54e8-006f-4605-8760-ed117d57fc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountLoginIndexUserName&quot;)</value>
      <webElementGuid>665150ec-3bad-46ae-a8f9-8495f8456678</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccountLoginIndexUserName']</value>
      <webElementGuid>9806bb15-8f07-47aa-bfc6-0fcc6140d291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/section[2]/div/div[2]/div/div/form/div[2]/input</value>
      <webElementGuid>8eeaacc5-90a2-41e9-9d8f-5f83db98f20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4c12f1d1-8115-4474-ae85-ec81d55f474a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccountLoginIndexUserName' and @type = 'text' and @name = 'Input.Username']</value>
      <webElementGuid>5b8efa72-13e2-4eae-81a0-4b7e3dc97b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
